### ISSUE TITLE
Unable to connect to Slack. Bad network?

### ISSUE THREAD

**Issue by bsmoo** [llimllib/limbo#109]
Hi Bill,

Sorry I'm setting this up on a new machine and I'm probably doing something wrong. I've followed the installation instructions but I'm getting the below error:
```
2017-07-13 22:18:25,957:WARNING:limbo.limbo:Unable to connect to Slack. Bad network?
Traceback (most recent call last):
  File "bin/limbo", line 17, in <module>
    main(args)
  File "/usr/lib/python2.7/site-packages/limbo-5.6.4-py2.7.egg/limbo/limbo.py", line 288, in main
    server.slack.rtm_connect()
  File "/usr/lib/python2.7/site-packages/limbo-5.6.4-py2.7.egg/limbo/slack.py", line 120, in rtm_connect
    self.connect_slack_websocket(self.ws_url)
  File "/usr/lib/python2.7/site-packages/limbo-5.6.4-py2.7.egg/limbo/slack.py", line 140, in connect_slack_websocket
    raise SlackConnectionError
limbo.slack.SlackConnectionError
```

Am I missing something simple?

**Comment by TetraEtc** [comment]
Not Bill.

It's either an error [here](https://github.com/websocket-client/websocket-client/blob/master/websocket/_core.py#L436) creating the websocket connection, or in where-ever line [Line 138 of limbo/slack.py](https://github.com/llimllib/limbo/blob/master/limbo/slack.py#L138) is apparently getting it's `setblocking` function from. 

In either case, I think we should add some nicer error checking here. 

It might be worth simply getting the exception that's been picked up, and passing that through, because right now it's entirely discarded.

**Comment by llimllib** [comment]
ugh yeah that's code I didn't write, that bare except is _ugly_. Sorry about that! @bsmoo are you still getting that?
