### ISSUE TITLE
crach when user connected

### ISSUE THREAD

**Issue by olanystrom** [llimllib/limbo#40]
It crached when a new user joined.
http://pastebin.com/peNPM7M8

**Comment by llimllib** [comment]
Thanks for the report, and sorry! Will investigate.

**Comment by llimllib** [comment]
Pasting the exception, in case the pastebin goes away:

```
limbo[6067]: Traceback (most recent call last):
limbo[6067]: File "/bin/limbo", line 5, in <module>
limbo[6067]: pkg_resources.run_script('limbo==3.0.2', 'limbo')
limbo[6067]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
limbo[6067]: self.require(requires)[0].run_script(script_name, ns)
limbo[6067]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
limbo[6067]: execfile(script_filename, namespace, namespace)
limbo[6067]: File "/usr/lib/python2.7/site-packages/limbo-3.0.2-py2.7.egg/EGG-INFO/scripts/limbo", line 17, in <module>
limbo[6067]: main(args)
limbo[6067]: File "/usr/lib/python2.7/site-packages/limbo-3.0.2-py2.7.egg/limbo/limbo.py", line 192, in main
limbo[6067]: loop(server)
limbo[6067]: File "/usr/lib/python2.7/site-packages/limbo-3.0.2-py2.7.egg/limbo/limbo.py", line 137, in loop
limbo[6067]: response = handle_event(event, server)
limbo[6067]: File "/usr/lib/python2.7/site-packages/limbo-3.0.2-py2.7.egg/limbo/limbo.py", line 114, in handle_event
limbo[6067]: return handler(event, server)
limbo[6067]: File "/usr/lib/python2.7/site-packages/limbo-3.0.2-py2.7.egg/limbo/limbo.py", line 102, in handle_message
limbo[6067]: if msguser["name"] == botname or msguser["name"].lower() == "slackbot":
limbo[6067]: TypeError: 'NoneType' object has no attribute '__getitem__'
```
