### ISSUE TITLE
can't connect proxy

### ISSUE THREAD

**Issue by enrico-bortolazzi** [llimllib/limbo#53]
Hi,
i tryed to launch your bot under proxy but i can't connect,
i can't find where define it in the code.

can you help me please?
this is the error i have:
Traceback (most recent call last):
  File "bin/limbo", line 17, in <module>
    main(args)
  File "/Library/Python/2.7/site-packages/limbo-3.5.1-py2.7.egg/limbo/limbo.py", line 247, in main
    server.slack.rtm_connect()
  File "/Library/Python/2.7/site-packages/slackrtm-0.2.1-py2.7.egg/slackrtm/client.py", line 14, in rtm_connect
    self.server.rtm_connect()
  File "/Library/Python/2.7/site-packages/slackrtm-0.2.1-py2.7.egg/slackrtm/server.py", line 61, in rtm_connect
    self.connect_slack_websocket(self.ws_url)
  File "/Library/Python/2.7/site-packages/slackrtm-0.2.1-py2.7.egg/slackrtm/server.py", line 80, in connect_slack_websocket
    raise SlackConnectionError
slackrtm.server.SlackConnectionError
make: *** [run] Error 1

**Comment by llimllib** [comment]
Enrico,

the slack library can't find the slack server; you need to run limbo in an environment where it can connect to slack.

I have no way of telling you how to do that in your environment, unfortunately.

-llimllib

**Comment by enrico-bortolazzi** [comment]
When i'm in a network without proxy all it's ok.
i think it's append because i haven't the proxy set in the code.
There are a way to insert it?
