### ISSUE TITLE
Adding new plugin just gives me errors?

### ISSUE THREAD

**Issue by blakesmoore** [llimllib/limbo#55]
When i add my own plugin, running '!help' just tried to run every single plugin and prints a bunch of errors similar to the below:

```
2015-10-29 10:04:08,502:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): secure.flickr.com
2015-10-29 10:04:10,017:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): encrypted.google.com
2015-10-29 10:04:10,581:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): en.wikipedia.org
2015-10-29 10:04:10,852:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com
2015-10-29 10:04:11,114:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.youtube.com
2015-10-29 10:04:11,415:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com
usage: limbo [-h] [--font FONT] [-l] [bannertext [bannertext ...]]
limbo: error: unrecognized arguments: option to list available fonts
2015-10-29 10:04:11,678:WARNING:limbo.limbo:Failed to run plugin <function on_message at 0x7f1d28ee8938>, module not loaded
2015-10-29 10:04:11,678:WARNING:limbo.limbo:<type 'exceptions.SystemExit'>
2015-10-29 10:04:11,679:WARNING:limbo.limbo:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/limbo-3.7.0-py2.7.egg/limbo/limbo.py", line 99, in run_hook
    h = hook(*args)
  File "/usr/local/lib/python2.7/dist-packages/limbo-3.7.0-py2.7.egg/limbo/plugins/banner.py", line 40, in on_message
    return make_banner(match[0])
  File "/usr/local/lib/python2.7/dist-packages/limbo-3.7.0-py2.7.egg/limbo/plugins/banner.py", line 20, in make_banner
    ns = ARGPARSE.parse_args(query.split(" "))
  File "/usr/lib/python2.7/argparse.py", line 1704, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python2.7/argparse.py", line 2374, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/usr/lib/python2.7/argparse.py", line 2362, in exit
    _sys.exit(status)
SystemExit: 2

2015-10-29 10:04:11,681:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.shutterstock.com
2015-10-29 10:04:12,276:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): encrypted.google.com
2015-10-29 10:04:12,764:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): whatthecommit.co
```

**Comment by blakesmoore** [comment]
Just realised i'm being a derp... need coffee...
```
./bin/limbo --pp limbo/plugins
```

**Comment by llimllib** [comment]
no problem! feel free to keep reporting issues, and that banner plugin exception looks like something I ought to look into anyway.
