### ISSUE TITLE
Module not loaded

### ISSUE THREAD

**Issue by gallart** [llimllib/limbo#67]
On a basic installation I have many modules which do not work with some of the default plugins.

Example : `!youtube madonna`

Server logs :

```
myserver limbo # ./bin/limbo --pluginpath limbo/plugins/
2016-03-01 14:15:34,498:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.youtube.com
2016-03-01 14:15:34,817:WARNING:limbo.limbo:Failed to run plugin <function on_message at 0x7f053e893f50>, module not loaded
2016-03-01 14:15:34,817:WARNING:limbo.limbo:<type 'exceptions.TypeError'>
2016-03-01 14:15:34,820:WARNING:limbo.limbo:Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/limbo-3.8.0-py2.7.egg/limbo/limbo.py", line 103, in run_hook
    h = hook(*args)
  File "limbo/plugins/youtube.py", line 30, in on_message
    return youtube(searchterm.encode("utf8"))
  File "limbo/plugins/youtube.py", line 15, in youtube
    r = requests.get(url)
  File "/usr/lib64/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```

**Comment by llimllib** [comment]
thank you very much for the report, will look into it

**Comment by llimllib** [comment]
OK, it looks like this is related to a urllib3 bug via requests: https://github.com/shazow/urllib3/issues/556

I have a branch already prepared that updates our version of the `requests` package (as well as a few others), which I hope should eliminate this bug. If I merge it can you try it out to see if it resolves your issue?

**Comment by gallart** [comment]
If course, I can see if it resolves.

I can also switch to this specific branch if you'd like.

**Comment by llimllib** [comment]
Thanks, if you want to try it's the `upgrade-requirements` branch

**Comment by gallart** [comment]
Same issues with upgrade-requirements branch.

**Comment by gallart** [comment]
But error is different :

```
SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)
```

**Comment by llimllib** [comment]
Thank you so much for the report.

ah ha, well that's good to know at least; the problem was that with the old requests/urllib3 bug, we couldn't know if it was an SSL cert problem or a timeout. Now we can see that it seems your installation is failing to properly request `https://youtube.com` due to certificate issues.

ATM, I'm at a bit of a loss for how to fix this problem, as I can't reproduce it :(

**Comment by llimllib** [comment]
Can you tell me your OS version? I can try and install a VM to reproduce this I guess?

**Comment by gallart** [comment]
Gentoo Linux (latest version).

2016-03-01 16:00 GMT+01:00 Bill Mill <notifications@github.com>:

**Comment by llimllib** [comment]
After much wailing and gnashing of teeth, I have reproduced this problem. It appears that, if you have OpenSSL 1.0.1 and certifi installed, cross-signed certificates (used by amazon, google, and others) will not be handled correctly.

This comment gives the possible workarounds: https://github.com/certifi/python-certifi/issues/26#issuecomment-138336586

In my testing, setting the `REQUESTS_CA_BUNDLE` environment variable to the output of `python -c 'import certifi; print certifi.old_where()'` stopped the errors from occurring. Presumably, upgrading to OpenSSL 1.0.2 would also fix the problem, but I haven't yet tried that.

Can you try setting the `REQUESTS_CA_BUNDLE` and seeing if that solves the problem?
